import "./globals.css";

export const metadata = {
  title: "Chris Shopping Cart",
  description: "Generated by Chris",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
